Update deploy-app.yml

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -1,12 +1,12 @@
 on:
-  pull_request:
+  push:
     branches:
       - main
   workflow_dispatch:
     inputs:
-      build-x-version:
+      build-new-version:
         description: 'Build now and deploy the app'
-        default: 'latest'
+        default: 'true'
         required: false
 
 jobs:
@@ -22,6 +22,20 @@ jobs:
           name: "firebase-service-account.json"
           json: ${{ secrets.FIREBASE_CREDENTIALS }}
           dir: 'src/'
+
+      - name: Docker meta data for image
+        id: meta
+        uses: docker/metadata-action@v4
+        with:
+          images: |
+            ${{ secrets.DOCKER_USERNAME }}/backend-user-app:latest
+          tags: |
+            type=raw,value=latest
+            type=ref,event=branch
+            type=ref,event=pr
+            type=semver,pattern={{version}}
+            type=semver,pattern={{major}}.{{minor}}
+            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
 
       - name: Docker login        
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
@@ -61,4 +75,10 @@ jobs:
             docker stop backend-user-app || true
             docker rm backend-user-app || true
             docker run --env-file .env -d --name backend-user-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/backend-user-app:latest
+            # Check the container is up and running, if not then fail workflow
+            if ! docker ps --filter "name=backend-user-app:latest" --filter "status=running" --format '{{.Names}}' | grep -w backend-user-app:latest > /dev/null; then
+              echo "Container is not running, exiting..."
+              exit 1
+            fi
+
 
